"""empty message

Revision ID: 085e6a69eefd
Revises: 4164266a8d3a
Create Date: 2018-10-10 12:54:31.872658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085e6a69eefd'
down_revision = '4164266a8d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('preference', sa.String(), nullable=True))
    op.drop_column('user_preferences', 'toggle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('toggle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('preferences', 'preference')
    # ### end Alembic commands ###
