"""empty message

Revision ID: 3433a9fdfcc5
Revises: bef7ad4ce2da
Create Date: 2018-09-11 14:29:38.586540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3433a9fdfcc5'
down_revision = 'bef7ad4ce2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('label', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('active', sa.Boolean(), server_default='0', nullable=False))
    op.add_column(u'user', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=255), server_default='', nullable=False))
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column(u'user', 'admin')
    op.drop_column(u'user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'email_confirmed_at')
    op.drop_column(u'user', 'active')
    op.drop_table('users_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
