"""empty message

Revision ID: 4164266a8d3a
Revises: d2a1d8802208
Create Date: 2018-10-10 12:42:31.618664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4164266a8d3a'
down_revision = 'd2a1d8802208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'toggle')
    op.add_column('user_preferences', sa.Column('toggle', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'toggle')
    op.add_column('preferences', sa.Column('toggle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
