"""empty message

Revision ID: 4f50a104b079
Revises: 896c74c8d976
Create Date: 2018-07-08 20:30:37.222829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f50a104b079'
down_revision = '896c74c8d976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(length=20), nullable=True),
    sa.Column('q2', sa.String(length=20), nullable=True),
    sa.Column('q2a', sa.String(length=255), nullable=True),
    sa.Column('q2b', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('survey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('q1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('q2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('q2a', sa.VARCHAR(length=255), nullable=True),
    sa.Column('q2b', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('survey_model')
    # ### end Alembic commands ###
