"""empty message

Revision ID: 5e58044ee56a
Revises: 085e6a69eefd
Create Date: 2018-11-02 13:23:23.529232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e58044ee56a'
down_revision = '085e6a69eefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('started_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'started_on')
    # ### end Alembic commands ###
