"""empty message

Revision ID: 647a92955657
Revises: 5e58044ee56a
Create Date: 2018-11-15 09:01:47.001368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647a92955657'
down_revision = '5e58044ee56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
