"""empty message

Revision ID: d2a1d8802208
Revises: 4fad68c22961
Create Date: 2018-10-10 12:39:57.976418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a1d8802208'
down_revision = '4fad68c22961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('toggle', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'toggle')
    # ### end Alembic commands ###
