"""empty message

Revision ID: e14e924078b2
Revises: f1c8ac32509c
Create Date: 2018-09-21 11:13:02.725540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14e924078b2'
down_revision = 'f1c8ac32509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('completed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'completed_on')
    # ### end Alembic commands ###
